### ISSUE TITLE
Possible issue with mkfifo

### ISSUE THREAD

**Issue by azurillandfriend** [jlanga/smsk_popoolation#20]
I got the following error while running the example dataset. The file 2R.mpileup.log is empty - possibly a problem with fifo. System administrator checked and mkfifo is definitely installedon the system being used. The version installed is 8.28.
System administrator also tried recreating the software (running the snakemake pipeline) on another of our development machines and hit other problems with packages that are definitely installed but it doesn’t seem to like it. 
I'm currently testing the popoolation2 part by running each step separately from command line.

Activating conda environment: /home/dyern/lstm_scratch/smsk_popoolation/.snakemake/conda/5af75ca214322542d38ca9626894a8ef

mkfifo: cannot create fifo 'results/mpileup/filt/pop2/pop2.2R.mpileup': Operation not permitted

[Mon Dec  6 12:29:00 2021]

Error in rule mpileup_popoolation_filter_indels:

    jobid: 27

    output: results/mpileup/filt/pop2/pop2.2R.mpileup, results/mpileup/filt/pop2/pop2.2R.mpileup.gz

    log: results/mpileup/filt/pop2/pop2.2R.mpileup.log (check log file(s) for error message)

    conda-env: /home/dyern/lstm_scratch/smsk_popoolation/.snakemake/conda/5af75ca214322542d38ca9626894a8ef

    shell:

       

        mkfifo results/mpileup/filt/pop2/pop2.2R.mpileup

 

        (cat results/mpileup/filt/pop2/pop2.2R.mpileup | gzip --fast > results/mpileup/filt/pop2/pop2.2R.mpileup.gz &)

 

        perl src/popoolation_1.2.2/basic-pipeline/filter-pileup-by-gtf.pl             --input <(gzip --decompress --stdout results/mpileup/raw/pop2/pop2.2R.mpileup.gz)             --gtf results/mpileup/filt/pop2/pop2.2R.gtf             --output results/mpileup/filt/pop2/pop2.2R.mpileup         2> results/mpileup/filt/pop2/pop2.2R.mpileup.log 1>&2

       

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

 

[Mon Dec  6 12:29:03 2021]

Finished job 6.

33 of 71 steps (46%) done

Shutting down, this might take some time.

Exiting because a job execution failed. Look above for error message

Complete log: /home/dyern/lstm_scratch/smsk_popoolation/.snakemake/log/2021-12-06T122740.426984.snakemake.log

**Comment by jlanga** [comment]
hmmm... FIFOs (first-in, first-out) are special files that act as pipes. I use them to trick popoolation to think that they are proper files, to gzip the output mpileup files as they come, because they are huge.

`mkfifo: cannot create fifo 'results/mpileup/filt/pop2/pop2.2R.mpileup': Operation not permitted` says that it is not possible to create a FIFO there. It may be because you are in a scratch partition. Maybe because the log in node and the working node are different. Maybe because the sysadmin has disabled them. Maybe because the worker cannot create them, but you can create them manually....

Can you create a fifo anywhere in that node (`mkfifo test`), and in that particular place?
Can you create a job that explicitelly creates them?

I don't know the sizes of your samples, number of populations and genomes, but it could be easier (surely not faster) to do it a server/desktop elsewhere. The last version of popoolation dates from 2011. ~75% of the work is read mapping and getting the raw mpileup files. The rest is patience.

**Comment by jlanga** [comment]
Hi @azurillandfriend, did you manage to create fifos in your cluster?

**Comment by azurillandfriend** [comment]
Not yet, I got distracted by another problem. Will try and get in touch with the administrator and get back to you.

thanks
Naomi
________________________________
